# settings.py

# --- Configurações da Tela e Jogo ---
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 900
FPS = 60
TOTAL_LEVELS = 10

# --- Cores ---
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
GRAY = (128, 128, 128)
BLUE_FINISH = (100, 100, 255)
DARK_GRAY = (50, 50, 50)
ORANGE = (255, 165, 0)
YELLOW = (255, 255, 0)
PLAYER_PROJECTILE_COLOR = (0, 200, 255) # Ciano para o projétil do jogador

# --- Configurações de Feedback Visual ---
FLASH_DURATION = 250
FLASH_COLOR = (200, 0, 0)
FLASH_ALPHA = 150

# --- Configurações do Jogador ---
PLAYER_WIDTH = 40
PLAYER_HEIGHT = 40
PLAYER_START_X = SCREEN_WIDTH / 2 - PLAYER_WIDTH / 2
PLAYER_START_Y = SCREEN_HEIGHT - PLAYER_HEIGHT
PLAYER_SPEED = 3
PLAYER_MAX_LIVES = 3
PLAYER_STARTING_AMMO = 3

# --- Configurações dos Carros ---
CAR_WIDTH = 80
CAR_HEIGHT = 40
CAR_BASE_SPEED_MIN = 1.5
CAR_BASE_SPEED_MAX = 3.0
CAR_SPEED_INCREMENT = 0.4
CAR_SPAWN_OFFSET = 100
CAR_SAFETY_DISTANCE = 15

# --- Configurações do Inimigo ---
ENEMY_WIDTH = 40
ENEMY_HEIGHT = 40
ENEMY_FIRE_RATE_MIN = 1500
ENEMY_FIRE_RATE_MAX = 3500
ENEMY_SPAWN_TOP_PERCENT = 0.6

# --- Configurações do Projétil do Inimigo ---
PROJECTILE_WIDTH = 8
PROJECTILE_HEIGHT = 20
PROJECTILE_SPEED = 7

# --- Configurações do Projétil do Jogador ---
PLAYER_PROJECTILE_WIDTH = 10
PLAYER_PROJECTILE_HEIGHT = 10
PLAYER_PROJECTILE_SPEED = 10

# --- Configurações das Pistas e Zonas Seguras ---
SAFE_ZONE_HEIGHT = 50
LANE_BLOCK_HEIGHT = CAR_HEIGHT + SAFE_ZONE_HEIGHT
NUM_LANES = 8
BOTTOM_LANE_Y = SCREEN_HEIGHT - 140
CAR_LANES_Y = [
    BOTTOM_LANE_Y - (i * LANE_BLOCK_HEIGHT) for i in range(NUM_LANES)
]

# --- Configurações da Linha de Chegada ---
FINISH_LINE_Y = 50
FINISH_LINE_HEIGHT = 50

# --- Configurações do Botão ---
BUTTON_WIDTH = 200
BUTTON_HEIGHT = 50
BUTTON_COLOR = BLUE_FINISH
BUTTON_TEXT_COLOR = WHITE
BUTTON_HOVER_COLOR = (150, 150, 255)